# Turtle Monitoring System - Binary Sensors Configuration
# Phase 1: Basic system binary sensors only (Simplified for Phase 2A)

# System connectivity sensors
- platform: ping
  host: 8.8.8.8
  name: "Internet Connection"
  scan_interval: 60

- platform: ping
  host: 10.0.20.1
  name: "Router Connection"
  scan_interval: 30

# Basic template binary sensors (simplified to avoid dependency issues)
- platform: template
  sensors:
    turtle_system_online:
      friendly_name: "Turtle System Online"
      icon_template: mdi:server-network
      value_template: >
        {{ is_state(binary_sensor.internet_connection, on) and
           is_state(binary_sensor.router_connection, on) }}
      device_class: connectivity
