# Turtle Monitoring System - Sensors Configuration
# Phase 1: Basic system sensors only (Fixed for Phase 2A)

# System monitoring sensors
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

# Time and date sensors
- platform: time_date
  display_options:
    - time
    - date
    - date_time

# Simple template sensors (minimal to avoid dependency issues)
- platform: template
  sensors:
    system_temperature:
      friendly_name: "System Temperature"
      icon_template: mdi:thermometer
      value_template: "72"
      unit_of_measurement: "°F"
      
    uptime_display:
      friendly_name: "System Uptime"
      icon_template: mdi:clock-outline
      value_template: >
        {% set last_boot = states('sensor.last_boot') %}
        {% if last_boot != 'unavailable' and last_boot != 'unknown' %}
          {% set uptime = as_timestamp(now()) - as_timestamp(last_boot) %}
          {% set days = (uptime // 86400) | int %}
          {% set hours = ((uptime % 86400) // 3600) | int %}
          {% set minutes = ((uptime % 3600) // 60) | int %}
          {{ days }}d {{ hours }}h {{ minutes }}m
        {% else %}
          Unknown
        {% endif %}
        
    # System status sensors for dashboard
    turtle_system_status:
      friendly_name: "System Status"
      icon_template: mdi:turtle
      value_template: >
        {% if is_state('input_boolean.turtle_maintenance_mode', 'on') %}
          Maintenance
        {% elif is_state('input_boolean.turtle_manual_mode', 'on') %}
          Manual
        {% elif is_state('input_boolean.turtle_system_armed', 'on') %}
          Armed
        {% else %}
          Disarmed
        {% endif %}
        
    turtle_system_health:
      friendly_name: "System Health" 
      icon_template: >
        {% set cpu = states('sensor.processor_use') | default(0) | float %}
        {% set memory = states('sensor.memory_use_percent') | default(0) | float %}
        {% set disk = states('sensor.disk_use_percent_home') | default(0) | float %}
        {% if cpu > 80 or memory > 90 or disk > 90 %}
          mdi:alert-circle
        {% elif cpu > 60 or memory > 75 or disk > 75 %}
          mdi:alert
        {% else %}
          mdi:check-circle
        {% endif %}
      value_template: >
        {% set cpu = states('sensor.processor_use') | default(0) | float %}
        {% set memory = states('sensor.memory_use_percent') | default(0) | float %}
        {% set disk = states('sensor.disk_use_percent_home') | default(0) | float %}
        {% if cpu > 80 or memory > 90 or disk > 90 %}
          Critical
        {% elif cpu > 60 or memory > 75 or disk > 75 %}
          Warning
        {% else %}
          Good
        {% endif %}
        
    # Placeholder environmental sensors (Phase 2)
    turtle_temperature_placeholder:
      friendly_name: "Temperature" 
      icon_template: mdi:thermometer
      value_template: "72"
      unit_of_measurement: "°F"
      
    turtle_humidity_placeholder:
      friendly_name: "Humidity"
      icon_template: mdi:water-percent
      value_template: "65"
      unit_of_measurement: "%"
