# Turtle Monitoring System - Sensors Configuration
# Phase 1: Basic system sensors only (Fixed for Phase 2A)

# System monitoring sensors
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot

# Time and date sensors
- platform: time_date
  display_options:
    - time
    - date
    - date_time

# Simple template sensors (minimal to avoid dependency issues)
- platform: template
  sensors:
    system_temperature:
      friendly_name: "System Temperature"
      icon_template: mdi:thermometer
      value_template: "72"
      unit_of_measurement: "°F"
      
    uptime_display:
      friendly_name: "System Uptime"
      icon_template: mdi:clock-outline
      value_template: >
        {% set uptime = as_timestamp(now()) - as_timestamp(states(sensor.last_boot)) %}
        {% set days = (uptime // 86400) | int %}
        {% set hours = ((uptime % 86400) // 3600) | int %}
        {% set minutes = ((uptime % 3600) // 60) | int %}
        {{ days }}d {{ hours }}h {{ minutes }}m
