# Turtle Habitat Sensors Configuration
# MQTT-based sensor integration for TEMPerHUM USB sensors

# Sensor 1 - Temperature (Celsius)
- platform: mqtt
  name: "Turtle Habitat Temperature 1 (°C)"
  unique_id: turtle_temperhum_temp1_c
  state_topic: "turtle/sensors/temperhum/sensor_1"
  value_template: "{{ value_json.temperature_c }}"
  unit_of_measurement: "°C"
  device_class: temperature
  availability_topic: "turtle/sensors/temperhum/sensor_1"
  availability_template: "{{ value_json.timestamp is defined }}"
  json_attributes_topic: "turtle/sensors/temperhum/sensor_1"
  json_attributes_template: "{{ {'humidity': value_json.humidity, 'interval': value_json.interval, 'timestamp': value_json.timestamp} | tojson }}"

# Sensor 1 - Temperature (Fahrenheit)
- platform: mqtt
  name: "Turtle Habitat Temperature 1 (°F)"
  unique_id: turtle_temperhum_temp1_f
  state_topic: "turtle/sensors/temperhum/sensor_1"
  value_template: "{{ value_json.temperature_f }}"
  unit_of_measurement: "°F"
  device_class: temperature
  availability_topic: "turtle/sensors/temperhum/sensor_1"
  availability_template: "{{ value_json.timestamp is defined }}"

# Sensor 1 - Humidity
- platform: mqtt
  name: "Turtle Habitat Humidity 1"
  unique_id: turtle_temperhum_humidity1
  state_topic: "turtle/sensors/temperhum/sensor_1"
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: "%"
  device_class: humidity
  availability_topic: "turtle/sensors/temperhum/sensor_1"
  availability_template: "{{ value_json.timestamp is defined }}"

# Sensor 2 - Temperature (Celsius)
- platform: mqtt
  name: "Turtle Habitat Temperature 2 (°C)"
  unique_id: turtle_temperhum_temp2_c
  state_topic: "turtle/sensors/temperhum/sensor_2"
  value_template: "{{ value_json.temperature_c }}"
  unit_of_measurement: "°C"
  device_class: temperature
  availability_topic: "turtle/sensors/temperhum/sensor_2"
  availability_template: "{{ value_json.timestamp is defined }}"
  json_attributes_topic: "turtle/sensors/temperhum/sensor_2"
  json_attributes_template: "{{ {'humidity': value_json.humidity, 'interval': value_json.interval, 'timestamp': value_json.timestamp} | tojson }}"

# Sensor 2 - Temperature (Fahrenheit)
- platform: mqtt
  name: "Turtle Habitat Temperature 2 (°F)"
  unique_id: turtle_temperhum_temp2_f
  state_topic: "turtle/sensors/temperhum/sensor_2"
  value_template: "{{ value_json.temperature_f }}"
  unit_of_measurement: "°F"
  device_class: temperature
  availability_topic: "turtle/sensors/temperhum/sensor_2"
  availability_template: "{{ value_json.timestamp is defined }}"

# Sensor 2 - Humidity
- platform: mqtt
  name: "Turtle Habitat Humidity 2"
  unique_id: turtle_temperhum_humidity2
  state_topic: "turtle/sensors/temperhum/sensor_2"
  value_template: "{{ value_json.humidity }}"
  unit_of_measurement: "%"
  device_class: humidity
  availability_topic: "turtle/sensors/temperhum/sensor_2"
  availability_template: "{{ value_json.timestamp is defined }}"

# TEMPerHUM Manager Status
- platform: mqtt
  name: "TEMPerHUM Manager Status"
  unique_id: turtle_temperhum_manager_status
  state_topic: "turtle/sensors/temperhum/status"
  value_template: "{{ value_json.status }}"
  availability_topic: "turtle/sensors/temperhum/status"
  availability_template: "{{ value_json.timestamp is defined }}"
  json_attributes_topic: "turtle/sensors/temperhum/status"
  json_attributes_template: "{{ {'sensors_active': value_json.sensors_active, 'last_update': value_json.timestamp} | tojson }}"
