version: '3.8'

services:
  turtle-api:
    build:
      context: ../api
      dockerfile: Dockerfile
    container_name: turtle-monitor-api
    ports:
      - "8000:8000"
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - DATABASE_PATH=/data/turtle_monitor.db
    volumes:
      - turtle_data:/data
      - ../frontend:/app/frontend:ro
    networks:
      - turtle_network
    depends_on:
      - mosquitto
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: turtle-monitor-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ../config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mqtt_data:/mosquitto/data
      - mqtt_logs:/mosquitto/log
    networks:
      - turtle_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  turtle_data:
    driver: local
  mqtt_data:
    driver: local
  mqtt_logs:
    driver: local

networks:
  turtle_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 